# Generated by Django 5.1.2 on 2024-11-03 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagoda__app', '0002_alter_city_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='USerCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'cities',
            },
        ),
    ]
