# Generated by Django 5.1.2 on 2024-10-29 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagoda__app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'cities'},
        ),
    ]
