# Generated by Django 5.1.2 on 2024-11-03 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagoda__app', '0003_usercity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercity',
            options={'verbose_name_plural': 'user_cities'},
        ),
    ]
