# Generated by Django 5.1.2 on 2024-11-04 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagoda__app', '0004_alter_usercity_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercity',
            old_name='user_name',
            new_name='name',
        ),
    ]
